# -*- coding: utf-8 -*-
"""Model_proyek Predictive Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfiF60Mrs52SDszKgqCMGo5W7L_etM4_

# Proyek Pertama [Predictive Analytics]: Pima Indians Diabetes Database
- **Nama:** Permata Ayu Rahmawati
- **Email:** permathaayu21@gmail.com

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, RocCurveDisplay
from xgboost import XGBClassifier, plot_importance
from imblearn.pipeline import Pipeline as imbpipeline
from imblearn.over_sampling import SMOTE
import pickle
from google.colab import files

"""## Data Preparation

### Data Loading
"""

# Upload kaggle.json
uploaded = files.upload()

# Setup Kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d uciml/pima-indians-diabetes-database
!unzip pima-indians-diabetes-database.zip

# Load dataset
df = pd.read_csv('diabetes.csv')

"""## EDA(Exploratory Data Analyst)

### Data Info
"""

def perform_eda(df):
    """Fungsi untuk melakukan EDA lengkap"""
    # 3.1. Data Overview
    print("\n=== Data Overview ===")
    print(df.info())
    print("\nDescriptive Statistics:")
    print(df.describe())

# Check missing values (nilai 0)
medical_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
print("\n=== Persentase Nilai 0 ===")
for col in medical_features:
  zero_percent = (df[col] == 0).mean() * 100
print(f"{col}: {zero_percent:.1f}%")

"""### Data Visualisasi"""

plt.figure(figsize=(12,8))

# Distribusi Target
plt.subplot(2,2,1)
sns.countplot(x='Outcome', data=df)
plt.title('Distribusi Diabetes (0: Sehat, 1: Diabetes)')

# Distribusi Fitur
plt.subplot(2,2,2)
sns.histplot(df['Glucose'], kde=True)
plt.title('Distribusi Glucose')

# Boxplot
plt.subplot(2,2,3)
sns.boxplot(data=df[medical_features])
plt.title('Deteksi Outlier')
plt.xticks(rotation=45)

# Correlation Matrix
plt.subplot(2,2,4)
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Korelasi Antar Fitur')

plt.tight_layout()
plt.savefig('eda_results.png')
plt.show()

perform_eda(df)

"""### Korelasi Matriks

## Preprocessing
"""

# Handle missing values (0)
medical_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in medical_features:
    df[col] = df[col].replace(0, df[col].median())

# Split data
X = df.drop('Outcome', axis=1)
y = df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Handle Class Imbalance
print("\nClass Distribution Before SMOTE:", y_train.value_counts())
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
print("Class Distribution After SMOTE:", pd.Series(y_train_res).value_counts())

"""## Model"""

# 5. BASE MODEL XGBOOST
base_model = XGBClassifier(random_state=42, eval_metric='logloss')
base_model.fit(X_train, y_train)

# Evaluasi
print("=== Baseline XGBoost ===")
print(classification_report(y_test, base_model.predict(X_test)))
print("ROC-AUC:", roc_auc_score(y_test, base_model.predict_proba(X_test)[:, 1]))

"""## Hyperparameter Tuning"""

# TUNED MODEL XGBOOST
# Pipeline
pipeline = imbpipeline([
    ('scaler', StandardScaler()),
    ('xgb', XGBClassifier(random_state=42, eval_metric='logloss'))
])

# Improved Parameter Grid
param_grid = {
    'xgb__max_depth': [3, 5, 7],
    'xgb__learning_rate': [0.001, 0.01, 0.1],
    'xgb__n_estimators': [100, 200, 300],
    'xgb__gamma': [0, 0.1, 0.2],
    'xgb__subsample': [0.8, 1.0]
}

# Initialize StratifiedKFold
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Grid Search
grid = GridSearchCV(
    pipeline,
    param_grid,
    scoring='roc_auc',
    cv=cv,  # Menggunakan StratifiedKFold yang sudah diinisialisasi
    n_jobs=-1,
    verbose=2
)
grid.fit(X_train_res, y_train_res)

# Best model
best_model = grid.best_estimator_
print("\nBest Parameters:", grid.best_params_)
print("Best CV AUC:", grid.best_score_)

"""## Evaluasi"""

# Evaluate
print("\n=== Tuned XGBoost ===")
print(classification_report(y_test, best_model.predict(X_test)))
print("ROC-AUC:", roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1]))

"""### visualisasi akhir"""

# VISUALIZATION
# Feature Importance
plt.figure(figsize=(10,6))
plot_importance(best_model.named_steps['xgb'])
plt.title('Feature Importance')
plt.show()

# Confusion Matrix
ConfusionMatrixDisplay.from_estimator(best_model, X_test, y_test)
plt.title('Confusion Matrix')
plt.show()

# ROC Curve
RocCurveDisplay.from_estimator(best_model, X_test, y_test)
plt.title('ROC Curve')
plt.show()

"""## Penyimpanan Model"""

## 7. Model Saving
# Save the best model
with open('diabetes_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)
print("\nModel saved as diabetes_model.pkl")

"""## Prediksi"""

# 7. SAMPLE PREDICTION
sample = [[6, 148, 72, 35, 0, 33.6, 0.627, 50]]  # Contoh data pasien
pred = best_model.predict(sample)
proba = best_model.predict_proba(sample)[0][1]

print(f"\nPrediction: {'Diabetes' if pred[0] == 1 else 'Healthy'}")
print(f"Probability: {proba*100:.2f}%")